export const MODIFICA_EMAIL = 'modifica_email';
export const MODIFICA_SENHA = 'modifica_senha';
export const MODIFICA_SENHA_CONF = 'modifica_senha_conf'
export const MODIFICA_NOME = 'modifica_nome';
export const CADASTRO_USUARIO_SUCESSO = 'cadastro_usuario_sucesso';
export const CADASTRO_USUARIO_ERRO = 'cadastro_usuario_erro';
export const CADASTRO_USUARIO_ERRO_SENHA = 'cadastro_usuario_erro_senha';
export const LOGIN_USUARIO_SUCESSO = 'login_usuario_sucesso';
export const LOGIN_USUARIO_ERRO = 'login_usuario_erro';
export const LOGIN_EM_ANDAMENTO = 'login_em_andamento';
export const CADASTRO_EM_ANDAMENTO = 'cadastro_em_andamento';
export const MODIFICA_PLACA =  'modifica_placa';
export const MODIFICA_QUILOMETRAGEM = 'modifica_quilometragem';
export const MODIFICA_ANO = 'modifica_ano';
export const MODIFICA_DATA_REVISAO = 'modifica_data_revisao';
export const MODIFICA_KM_RECOMENDADA = 'modifica_km_recomendada';
export const MODIFICA_APELIDO = 'modifica_apelido';
export const ADICIONA_VEICULO_SUCESSO = 'cadastro_veiculo_inclusao';
export const ADICIONA_VEICULO_ERRO = 'cadastro_veiculo_erro';
export const CADASTRO_VEICULO_EM_ANDAMENTO = 'cadastro_veiculo_em_andamento';
export const LISTA_VEICULO_USUARIO = 'lista_veiculo_usuario';
export const MODIFICA_NOME_LOCAL = 'modifica_nome_local';
export const MODIFICA_RESPONSAVEL = 'modifica_responsavel';
export const MODIFICA_ENDERECO = 'modifica_endereco';
export const ADICIONA_LOCAL_SUCESSO = 'adiciona_local_sucesso';
export const ADICIONA_LOCAL_ERRO = 'adiciona_local_erro';

export const MODIFICA_PECA = 'modifica_peca';
export const MODIFICA_DESCRICAO_PECA = 'modifica_descricao_peca';
export const ADICIONA_PECA_SUCESSO = 'adiciona_peca_sucesso';
export const ADICIONA_PECA_ERRO = 'adiciona_peca_erro';

export const LISTA_VEICULO_USUARIO_DROP= 'lista_veiculo_usuario_drop';
export const LISTA_PECA_DROP= 'lista_peca_drop';